name: Check
on: [push, pull_request]
permissions:
  contents: read
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['22.12.0', '24']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@f520eceda224fe1a4aed5a2a27a194379a409996 # v6
        with:
          cache: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check
      - run: pnpm run build
      - run: pnpm run test:e2e
        if: runner.os != 'Linux'
      - run: xvfb-run -a pnpm run test:e2e
        if: runner.os == 'Linux'
      - run: pnpm run pack
        if: runner.os == 'Windows'
      - run: pnpm exec electron-builder --config electron-builder.json --mac --dir --config.mac.identity=- --config.mac.notarize=false --publish never
        if: runner.os == 'macOS'
